### ISSUE TITLE
CF Workload Migration : Failed to decode JWT bearer: no 'Authorization' header present in request

### ISSUE THREAD

**Issue by NathanHayounSAP** [SAP/cloud-sdk-java#705]
### Ask the Question

Hello Team,

I am currently working on an extension landscape ([Official Guide](https://pages.github.tools.sap/cloudfoundry/dev-portal/cf-workload-migration/)) setup, where my Approuter is deployed on `eu12`, and my application is running on `eu12-002`.

To enable communication between them, I have configured a route in my Approuter as follows:
```yaml
- name: dest-rf-srv
  group: destinations
  properties:
      name: dest-rf-srv
      url: "https://${org}-${space}-grdc-rf-srv.internal.cfapps.eu12-002.hana.ondemand.com"
      forwardAuthToken: true
      timeout: 300000
      setXForwardedHeaders: false
```

(I have also tested without `setXForwardedHeaders: false`, but the issue persists.)

However, when the request reaches my application, I encounter authentication-related errors:

```log
Setting property 'com.sap.cloud.sdk.cloudplatform.security.AuthTokenThreadContextListener:authToken' to value: Property(value=Failure(com.sap.cloud.sdk.cloudplatform.security.exception.AuthTokenAccessException: Failed to decode JWT bearer: no 'Authorization' header present in request.)).

Setting property 'com.sap.cloud.sdk.cloudplatform.security.BasicAuthenticationThreadContextListener:basicAuthHeader' to value: Property(value=Failure(com.sap.cloud.sdk.cloudplatform.security.exception.BasicAuthenticationAccessException: Unable to resolve basic credentials: Received an 'Authorization' header without a value)

Setting property 'com.sap.cloud.sdk.cloudplatform.tenant.TenantThreadContextListener:tenant' to value: Property(value=Failure(com.sap.cloud.sdk.cloudplatform.tenant.exception.TenantAccessException: Failed to get current tenant.))
```
(For reference, I have attached the complete logs in the attached file.)
[logcloudsdk.log](https://github.com/user-attachments/files/18585896/logcloudsdk.log)

It seems that the Authorization header is not correctly forwarded, leading to authentication failures on the application side.

From now our assomption is link to domain of route `eu12` -> `eu12-002`. We have tried to make the same scenario with a space in same domain `eu12` service properly received and decode the JWT (after it just claims that audience is not correct beacause is not the same xsuaa instance) but in our case the xsuaa is the same because is an reference-instance 

Would you have any insights on what might be missing in the configuration to resolve this issue?

Thank you in advance for your help!

Best regards,
Nathan
